### ISSUE TITLE
wrong prefix for non-scipion users

### ISSUE THREAD

**Issue by azazellochg** [erneyramirez/relion_deepEMhancer_extRec#1]
Hi @erneyramirez! 

We found that the script fails for non-scipion users because relion files start with run_* prefix, not relion_* like in Scipion. I suppose the script could account for this by guessing the CONDA_ENV name

https://github.com/erneyramirez/relion_deepEMhancer_extRec/blob/c3bfb61504567b423781ad25a9551462b8a23a04/relion_deepEMhancer_extRec.py#L86

**Comment by hnndlp** [comment]
can confirm it will run by replacing it with run_ , but there are still a lot of other issues when running relion 4.0 directly

**Comment by erneyramirez** [comment]
You are both right!. I must modify the script to use it outside of Scipion. I will try to do it as soon as possible.
Thank you very much!

**Comment by erneyramirez** [comment]
I have uploaded some changes and I think it may work for non-scipion users. I will try to keep improving the script.
Thank you for your comments
